### ISSUE TITLE
Cannot Deploy Marketing Definitions

### ISSUE THREAD

**Issue by K-Cyganiak** [sitecorerick/constellation-sitecore9#9]
Hi,
Sitecore 10.0.1
Running in Docker Container

`<package id="Constellation.Feature.Redirects" version="10.0.3.29515" targetFramework="net48" />
`
I had to temporarly remove Redirector as it would not allow me to deploy marketing definitions. 
Error stack below:

```
2836 22:47:33 ERROR Application error.
Exception: System.ArgumentNullException
Message: Value cannot be null.
Parameter name: item
Source: Sitecore.Kernel
   at Sitecore.Diagnostics.Assert.ArgumentNotNull(Object argument, String argumentName)
   at Sitecore.ContentSearch.SitecoreIndexableItem..ctor(Item item)
   at Constellation.Feature.Redirects.Pipelines.HttpRequest.RedirectResolver.FindRedirectRecordFor(String oldLocalPath)
   at Constellation.Feature.Redirects.Pipelines.HttpRequest.RedirectResolver.Execute(HttpRequestArgs args)
   at (Object , Object )
   at Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args)
   at Sitecore.Pipelines.DefaultCorePipelineManager.Run(String pipelineName, PipelineArgs args, String pipelineDomain, Boolean failIfNotExists)
   at Sitecore.Pipelines.DefaultCorePipelineManager.Run(String pipelineName, PipelineArgs args, String pipelineDomain)
   at Sitecore.Web.RequestEventsHandler.OnPostAuthenticateRequest(HttpContextBase context)
   at Sitecore.Nexus.Web.HttpModule.‍⁬‎‌⁪​⁮​‪‪‌⁭‪⁮‭‏‮‫‭‫⁯⁮‎⁮⁭‮‎‍​⁫‭‏⁭‪‎⁪​⁮⁪‏‮(Object , EventArgs )
   at System.Web.HttpApplication.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
```

**Comment by sitecorerick** [comment]
If the redirect resolver is firing when not intended, you need to identify
the path in the URL that you want it to ignore and add it to the XML
configuration of the Redirect Resolver pipeline handler. Once done Redirect
Resolver will ignore requests starting with that path. By default most
"sitecore" URLs are excluded already, but most people are not using the
Marketing kit, so you may have a URL that I didn't catch.

Please let me know what settings you change so that I can update the
solution.

**Comment by K-Cyganiak** [comment]
Many thanks, somehow i missed this config. I just added "/api" to list as i do not think we would ever want to redirect any API calls. Initiall call for deploying Marketing Definitions is "api/sitecore/DeployMarketingDefinitions/DeployDefinitions".
FYI error only happened in Docker setup though, our other envs did not experience this issue
